Desktop/lemonten/config/routes.rb
Rails.application.routes.draw do
 get 'pages/home'
  # get 'orders/index'
  # get 'orders/show'
  # get 'orders/new'
  # get 'orders/edit'
  root "pages#home"

  resources :orders
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Desktop/lemonten/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Desktop/lemonten/app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
end

Desktop/lemonten/app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Desktop/lemonten/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Desktop/lemonten/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = current_user.orders.new
  end

  def create 
    @order = current_user.orders.new(order_params)
    if @order.save 
      redirect_to orders_path 
    else
      render "new"
    end
  end 

  def edit
    @uorder = current_user


  end

  def order_params 
    params.require(:order).permit(:name, :quntity, :table_number)
  end 

end

Desktop/lemonten/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

Desktop/lemonten/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/lemonten/app/helpers/orders_helper.rb
module OrdersHelper
end

Desktop/lemonten/app/helpers/pages_helper.rb
module PagesHelper
end

Desktop/lemonten/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lemonten</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"> <%= notice %></p>
       <p class="alert"> <%= alert %></p>
      <nav>
      <% if user_signed_in?%>
      <%= link_to "sign out ",destroy_user_session_path, method: :delete %>
      <%= link_to "Add Order" , new_order_path%>
      <%= link_to "All my order " ,orders_path %>
      <%else %>
      <%= link_to "Login",new_user_session_path%>
      <%= link_to "sign up ", new_user_registration_path%>
     
    
      <%end%>
      
     
      </nav>


    <%= yield %>
  </body>
</html>

Desktop/lemonten/app/views/orders/edit.html.erb
<h1>Orders#edit</h1>

<p>Update your orders please :</p> 
<%= form_for Order.new do |f| %>

    <div class="field" >
    <%= f.label :name %><br />
     <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
   </div>
  
   <div class="field">
     <%= f.label :quntity %><br />
     <%= f.number_field :quntity %>
   </div>
  
   <div class="field">
     <%= f.label :table_number %><br />
     <%= f.number_field :table_number  %>
   </div>
  
   <div class="actions">
     <%= f.submit "Submit" %>
   </div>
    
   <% end %>

Desktop/lemonten/app/views/orders/index.html.erb
<h1>All My  orders</h1>






<table >
    <thead>
        <tr>
            <th>Name |</th>
            <th>Quntity |</th>
            <th>Table number  </th>
        </tr>
    </thead>


    <tbody>
    <% current_user.orders.each do |order| %>

       <tr> <td><%= order.name %></td>  
         <td><%= order.quntity %></td> 
         <td><%= order.table_number %></td>  
        <td>
         <button >delete</button>
          <td>
            <%= link_to "Update", edit_order_path(order) %>
            <%= link_to "Show", order_path(order) %>
        </td> </tr> 
    <% end %>
</tbody>
    
</table>

Desktop/lemonten/app/views/orders/new.html.erb
<h1>Orders#new</h1>

<p>Add your orders please :</p>
<%= form_for @order do |f|%>
<div class="field" >
  <%= f.label :name %><br />
   <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
 </div>

 <div class="field">
   <%= f.label :quntity %><br />
   <%= f.number_field :quntity %>
 </div>

 <div class="field">
   <%= f.label :table_number %><br />
   <%= f.number_field :table_number  %>
 </div>

 <div class="actions">
   <%= f.submit "Submit" %>
 </div>
<% end %> 

Desktop/lemonten/app/views/orders/show.html.erb
<h1>Orders#show</h1>

<p>Find me in app/views/orders/show.html.erb</p>

Desktop/lemonten/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<% if user_signed_in? %>
<h2>welcome 
    <%= current_user.email%> to your page </h2>
    <p>if you want to add your order please press on the   "add order"</p>
<% end %>


<h3>What is Lemonten coffee ?</h3>
<p>Is a café that offers coffee, cold and hot drinks, fresh juices and fresh baked goods 
at reasonable prices </p>